{
 "title": "zabbix",
 "time": { "from": "2021-02-09T23:25:52.390Z", "to": "2021-02-10T11:25:52.390Z" },
 "templating": {
  "list": [
   {
    "name": "group",
    "query": {}
   },
   {
    "name": "host",
    "query": {}
   },
   {
    "name": "Application",
    "query": {}
   },
   {
    "name": "liteams",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "系统运行时间",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "centos" },
     "host": { "filter": "aliyun-202" },
     "item": { "filter": "System uptime" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "cpu核数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "centos" },
     "host": { "filter": "aliyun-202" },
     "item": { "filter": "CPU核数" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "$Application" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "cpu使用率" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": " 内存使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "$Application" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "memory used percent" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "根分区使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/上使用的磁盘空间百分比" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "挂载磁盘使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "$Application" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$liteams" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "磁盘总空间",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*上的总磁盘空间/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "总内存",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.负载*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "磁盘使用情况",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*上使用的磁盘空间百分比/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "服务器流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}